### PR TITLE
Remove Curator content since Curator is removed

### PR DESCRIPTION
**Pull request by Josh-L**
Product Version(s):

Issue:

Companion PRs:
Enterprise: https://github.com/tigera/calico-private/pull/7041
Operator: https://github.com/tigera/operator/pull/3054

Link to docs preview:

https://deploy-preview-1217--calico-docs-preview-next.netlify.app/calico-enterprise/next/reference/component-versions
https://deploy-preview-1217--calico-docs-preview-next.netlify.app/calico-enterprise/next/operations/fips/#before-you-begin

SME review:
- [ ] An SME has approved this change. 

DOCS review:
- [ ] A member of the docs team has approved this change.

Additional information:

Merge checklist:

- [ ] Deploy preview inspected wherever changes were made 
- [ ] Build completed successfully
- [ ] Test have passed

### CODE REVIEW

**Comment by ctauchen** [comment]
Hi @Josh-Tigera . I'm not at all familiar with this one. Can you provide more context, links to tickets, etc?

**Comment by Josh-L** [comment]
> Hi @Josh-Tigera . I'm not at all familiar with this one. Can you provide more context, links to tickets, etc?

Hi @ctauchen here is a link to the Jira issue used to track: https://tigera.atlassian.net/browse/EV-3291?atlOrigin=eyJpIjoiNTkxYmQzNmQxMWM4NGYyZWE5YWRjZWFhZDBkODhkZDciLCJwIjoiaiJ9

I have links to my operator and enterprise commits linked in the description. Basically Curator support is removed in the next version of Elasticsearch we'll be upgrading to, and currently doesn't always work the way we need it to today anyway so we're pulling the component out entirely.

**Review by bmckercher123 — COMMENTED** [review]
@Josh-Tigera es-curator is in Calico Cloud docs as well. Should releases.json be updated in CC? Also, you have changed in root, which is 3.19/ep1. Is the change only for 3.19/ep1 and CC equivalent?

**Comment by Josh-L** [comment]
> @Josh-Tigera es-curator is in Calico Cloud docs as well. Should releases.json be updated in CC? Also, you have changed in root, which is 3.19/ep1. Is the change only for 3.19/ep1 and CC equivalent?

Ah good catch, it should also be removed in CC so I've pushed those changes as well. The removal is not required in any particular commit so it's just whenever it goes in. I'm targeting main/master in operator and enterprise which I believe corresponds to 3.19 (unless the branch was cut already and I missed it).

**Comment by bmckercher123** [comment]
@Josh-Tigera Please rebase to pick up dead link fixes in /main. Your PR should build after that.

**Comment by Josh-L** [comment]
> @Josh-Tigera Please rebase to pick up dead link fixes in /main. Your PR should build after that.

@bmckercher123 I merged in an updated version of main

**Review by bmckercher123 — APPROVED** [review]
LGTM

**Pull request merged**
