### PR TITLE
[EV-4345] Fix LoadBalancer Helm doc ManagementCluster address def.

### PR DESCRIPTION
**Pull request by dimitri-nicolo**
Product Version(s):

Issue:

Link to docs preview:

SME review:
- [ ] An SME has approved this change. 

DOCS review:
- [ ] A member of the docs team has approved this change.

Additional information:

Merge checklist:

- [ ] Deploy preview inspected wherever changes were made 
- [ ] Build completed successfully
- [ ] Test have passed

### CODE REVIEW

**Review by bmckercher123 — APPROVED** [review]
I do not see this doc in the left nav: [calico-cloud/operations/comms/certificate-management.mdx]

**Comment by dimitri-nicolo** [comment]
> I do not see this doc in the left nav: [calico-cloud/operations/comms/certificate-management.mdx]

Thanks @bmckercher123, I've removed the CC changes.

**Comment by dimitri-nicolo** [comment]
@tigeraphil could you please review the proposed installation directions when using a LoadBalancer service for a management cluster.

[install-calico-enterprise](https://deploy-preview-1074--calico-docs-preview-next.netlify.app/calico-enterprise/next/multicluster/set-up-multi-cluster-management/helm-install/create-a-management-cluster-helm#install-calico-enterprise)

**Comment by tigeraphil** [comment]
Hi Dimitri,

Some of the technical details in this PR are a bit over my head ;)  What
feedback were you looking for from me?

Thanks,
Phil

*Phil DiCorpo*
Director of Product Management
Tigera
***@***.*** | M: +1 650-766 <+1-650-766-2167>-2167
Follow Tigera: Blog <https://blog.tigera.io/> | Twitter
<https://twitter.com/tigeraio> | LinkedIn
<https://www.linkedin.com/company/tigera/>
*Security and observability for containers, Kubernetes, and cloud*
<https://tigera.io/>

**Pull request merged**
