### PR TITLE
BGPFilter: Add docs for prefixLength params

### PR DESCRIPTION
**Pull request by mstansberry**
Product Version(s):
Calico
Calico Enterprise

Issue:
https://github.com/projectcalico/calico/issues/8376

Link to docs preview:

SME review:
- [ ] An SME has approved this change. 

DOCS review:
- [ ] A member of the docs team has approved this change.

Additional information:

Merge checklist:

- [ ] Deploy preview inspected wherever changes were made 
- [ ] Build completed successfully
- [ ] Test have passed

### CODE REVIEW

**Comment by ctauchen** [comment]
@caseydavenport PTAL, if you're already having a look at the related projectcalico issue.

**Comment by ctauchen** [comment]
@caseydavenport I see you closed the related issue in projectcalico. Can you take a look at this PR?

**Review by caseydavenport — APPROVED** [review]
LGTM, thanks @mstansberry!

**Comment by ctauchen** [comment]
Thanks, @mstansberry. LGTM

**Comment by ctauchen** [comment]
@mstansberry I can follow up with changes to versioned directories. Do these changes apply to versions earlier than 3.29 (OSS) or 3.20 EP2 (Enterprise)?

**Comment by mstansberry** [comment]
> @mstansberry I can follow up with changes to versioned directories. Do these changes apply to versions earlier than 3.29 (OSS) or 3.20 EP2 (Enterprise)?

I believe those will be the newest versions that get this feature. Will defer to @caseydavenport whether this is expected to make it into a patch release for 3.28 or not 👍

**Pull request merged**
