### PR TITLE
DOCS-1544: Fixes backport omission for OVNKubernetes/Calico swap command

### PR DESCRIPTION
**Pull request by ctauchen**
[An earlier PR](https://github.com/tigera/docs/pull/681/files) omitted changes to OSS 3.26. 

Product Version(s):

OSS 3.26

Issue:

https://tigera.atlassian.net/browse/DOCS-1544

Link to docs preview:

SME review:
- [ ] An SME has approved this change. 

DOCS review:
- [ ] A member of the docs team has approved this change.

Additional information:

Merge checklist:

- [ ] Deploy preview inspected wherever changes were made 
- [ ] Build completed successfully
- [ ] Test have passed

### CODE REVIEW

**Comment by ctauchen** [comment]
@hjiawei Can you confirm I've got this right?

**Comment by ctauchen** [comment]
CC @onong @lwr20

**Comment by onong** [comment]
@ctauchen, imo, a slightly better way would be what I have implemented in the CalicoVPP doc, ie,

`sed -i 's/networkType:.*/networkType: Calico/' install-config.yaml`

With `sed -i 's/\(OpenShiftSDN\|OVNKubernetes\)/Calico/' install-config.yaml` the problem is that it will change all occurrences indiscriminately. But, yes, tbh, I do not see that causing any issues :) Just saying.

**Comment by ctauchen** [comment]
> @ctauchen, imo, a slightly better way would be what I have implemented in the CalicoVPP doc, ie,
> 
> `sed -i 's/networkType:.*/networkType: Calico/' install-config.yaml`
> 
> With `sed -i 's/\(OpenShiftSDN\|OVNKubernetes\)/Calico/' install-config.yaml` the problem is that it will change all occurrences indiscriminately. But, yes, tbh, I do not see that causing any issues :) Just saying.

Thanks. For now, I'll stick with this because it's what we have everywhere else. If you think it's important, feel free to submit a global fix for review.

**Pull request merged**
