### PR TITLE
DOCS-Add-NodeLocal-DNSCache-to-ebpf

### PR DESCRIPTION
**Pull request by bmckercher123**
Add NodeLocal DNSCache to unsupported list

Product Version(s):
CE 3.17 and 3.18

Issue:
n/a

Link to docs preview:

SME review:
- [ ] An SME has approved this change. 

DOCS review:
- [x] A member of the docs team has approved this change.

Additional information:

Merge checklist:

- [x] Deploy preview inspected wherever changes were made 
- [x] Build completed successfully
- [x] Test passed

### CODE REVIEW

**Review by girishshankaran — APPROVED** [review]
LGTM

**Comment by lwr20** [comment]
Do we need to update the node-local-dns doc too?
https://github.com/tigera/docs/blob/main/calico-enterprise/networking/configuring/node-local-dns-cache.mdx

**Comment by bmckercher123** [comment]
@lwr20 The doc pattern we've established for epbf is to list all features that are not supported, rather than maintain ebpf unsupported across the numerous features. Windows and WireGuard are two other features that operate the same way. This can change when we adopt single-source tooling.

**Comment by lwr20** [comment]
Fair enough if that's the convention.  

(I have beef with that convention, but that's nothing to do with this PR.)

**Pull request merged**
