### PR TITLE
Update:  Link to new tutorials

### PR DESCRIPTION
**Pull request by frozenprocess**
Update:  Link to new tutorials

This PR adds the related Calico hands-on workshop to the documentation.

### CODE REVIEW

**Review by ctauchen — COMMENTED** [review]
Thanks, @frozenprocess! 

This look great. Only thing I'd like to see is more direct links to the courses.

There don't seem to be individual pages to link to. But maybe you could add a search query to the link? 

Something like this might help users get to where you need:
https://www.tigera.io/tutorials/?_sf_s=%27calico%20ebpf%20and%20xdp%27

**Comment by frozenprocess** [comment]
Thanks for the review @ctauchen, I've adjusted my commit with your suggestion.

**Comment by ctauchen** [comment]
@frozenprocess That's perfect, thanks! Now that that's squared away, you might consider copying the changes to the corresponding files in OS 3.25 and 3.24. Otherwise, the changes will make their way in the upcoming 3.26 release.

**Comment by frozenprocess** [comment]
Thanks @ctauchen, I almost forgot about this one :D

**Pull request merged**
