### PR TITLE
Updating to node v20.16.0

### PR DESCRIPTION
**Pull request by ctauchen**
During D3 upgrade testing I was unable to get a Netlify build because of a node dependency: https://app.netlify.com/sites/tigera/deploys/66c459730829770008b4ade8. 

We're currently on node 18, which is the minimum required for Docusaurus 3. Node 18 will be EOL on 2025-04-30.

This updates our build to node v20.16.0.

### CODE REVIEW

**Comment by ctauchen** [comment]
@ronanc-tigera @doucol 

This builds fine, but is it a good idea? Are there reasons to stick with 18?

**Comment by doucol** [comment]
> @ronanc-tigera @doucol
> 
> This builds fine, but is it a good idea? Are there reasons to stick with 18?

Should be fine, and possibly recommended to do the upgrade. would like to hear what Ronan thinks though

**Comment by ronanc-tigera** [comment]
If you're upgrading Node, you should also update the package.json with
```json
  "engines": {
    "node": ">=20.0"
  }
```
Assuming you ran & tested locally as well?

**Comment by ctauchen** [comment]
> ```json
>   "engines": {
>     "node": ">=20.0"
>   }
> ```

Thanks, I've added that and updated the readme. 

Local build and tests pass just fine.

**Review by ronanc-tigera — APPROVED** [review]

**Pull request merged**
