### PR TITLE
Update makefile and run make autogen

### PR DESCRIPTION
**Pull request by rene-dekker**

### CODE REVIEW

**Review by bmckercher123 — APPROVED** [review]
LGTM. The dead links should clear if you rebase.

**Comment by bmckercher123** [comment]
It is still failing. Please add the following link to skip list: __tests/crawler.test.js

http://www.gnu.org/philosophy/why-not-lgpl.html in

**Comment by doucol** [comment]
> It is still failing. Please add the following link to skip list: __tests/crawler.test.js
> 
> http://www.gnu.org/philosophy/why-not-lgpl.html in

This is getting a 302 for me and redirects you to http://www.gnu.org/licenses/why-not-lgpl.html  -- please fix the link rather than skipping.

**Comment by rene-dekker** [comment]
@doucol  @bmckercher123  I fixed the dead url, but I wonder if this will return at some point. Is this page generated by code from fossa scans?

**Comment by doucol** [comment]
> @doucol @bmckercher123 I fixed the dead url, but I wonder if this will return at some point. Is this page generated by code from fossa scans?

yeah... the test should handle redirects, so perhaps we just caught it at a point where it didn't exist and then the redirect was added.  idk!  I would just leave it as-is for now though.

**Review by coutinhop — APPROVED** [review]

**Pull request merged**
