### PR TITLE
Change URLs to relative paths

### PR DESCRIPTION
**Pull request by girishshankaran**
Related PR: https://github.com/tigera/docs/pull/577

Product Version(s):

Issue:

Link to docs preview:

SME review:
- [ ] An SME has approved this change. 

DOCS review:
- [ ] A member of the docs team has approved this change.

Additional information:

### CODE REVIEW

**Comment by girishshankaran** [comment]
@tmjd Can please you review this one?

**Comment by ctauchen** [comment]
LGTM, with bad link added to skip list (https://thenewstack.io/faster-troubleshooting-with-dynamic-packet-capture/ returns an erroneous 403)

**Comment by girishshankaran** [comment]
> LGTM, with bad link added to skip list (https://thenewstack.io/faster-troubleshooting-with-dynamic-packet-capture/ returns an erroneous 403)

Sure Chris.

**Review by tmjd — COMMENTED** [review]
I know it isn't needed from me but LGTM.

**Pull request merged**
