### PR TITLE
Setting vppbranch variable's value to v3.28.0

### PR DESCRIPTION
**Pull request by onong**
Setting vppbranch variable's value to v3.28.0

Product Version(s): v3.28.0

Issue:

Link to docs preview:

SME review:
- [ ] An SME has approved this change. 

DOCS review:
- [ ] A member of the docs team has approved this change.

Additional information:

Merge checklist:

- [ ] Deploy preview inspected wherever changes were made 
- [ ] Build completed successfully
- [ ] Test have passed

### CODE REVIEW

**Comment by onong** [comment]
@ctauchen , @lwr20 

Hi Guys, could you please review and merge this PR? We are cutting Calico/VPP v3.28.0 release and this is to make sure the docs point to the right release.

**Comment by ctauchen** [comment]
LGTM, pending clean build.

**Comment by ctauchen** [comment]
@onong Ready to merge?

**Comment by onong** [comment]
@ctauchen thanks!

**Pull request merged**
