### PR TITLE
Update kubectl command to be more robust

### PR DESCRIPTION
**Pull request by ghost**
Existing `kubectl create` command threw the following error
```
"https://raw.githubusercontent.com/projectcalico/calico/v3.26.1/manifests/tigera-operator.yaml": customresourcedefinitions.apiextensions.k8s.io "networkpolicies.crd.projectcalico.org" already exists
```
Advised to update to `kubectl apply` however this threw the error
```
The CustomResourceDefinition "installations.operator.tigera.io" is invalid: metadata.annotations: Too long: must have at most 262144 bytes
```
@lwr20 advised to extend the `kubectl apply` for robustness which seemed to work best
```
kubectl apply --server-side --force-conflicts
```

Product Version(s):
Calico only

Issue:
[CORE-9871](https://tigera.atlassian.net/browse/CORE-9871)

Link to docs preview:
[Migrate Calico to an operator-managed installation](https://docs.tigera.io/calico/latest/operations/operator-migration)

SME review:
- [ ] An SME has approved this change. 

DOCS review:
- [ ] A member of the docs team has approved this change.

Additional information:

Merge checklist:

- [ ] Deploy preview inspected wherever changes were made 
- [ ] Build completed successfully
- [ ] Test have passed 

[CORE-9871]: https://tigera.atlassian.net/browse/CORE-9871?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by ctauchen** [comment]
@StevenTigera Is this something that came up in testing for 3.27? Should we make corresponding changes elsewhere?

**Comment by ghost** [comment]
> @StevenTigera Is this something that came up in testing for 3.27? Should we make corresponding changes elsewhere?

No @ctauchen - my understanding is that as Calico can only currently be installed via manifests in OSS, i.e. not Calico Enterprise nor Cloud this is not a very common use case thus this may be have been an issue for quite some time?  I only stumbled onto this issue recently bychance and @lwr20 made this suggestion which helped me overcome the issue hence suggested I should retrofit into the docs - that's all - I hope this helps

**Comment by lwr20** [comment]
> Calico can only currently be installed via manifests in OSS

Operator install is definitely possible in OSS, and the preferred option.  I think we _should_ be making changes elsewhere too.  But @StevenTigera has only tested this particular case.

**Comment by ctauchen** [comment]
> Is this something that came up in testing for 3.27? Should we make corresponding changes elsewhere?

By elsewhere I meant more like OSS 3.26, 3.25, 3.24. Sorry, should have made that clearer. Assuming that this applies to those versions, copy the changes and we're good to go.

@StevenTigera

**Comment by ghost** [comment]
> > Is this something that came up in testing for 3.27? Should we make corresponding changes elsewhere?
> 
> By elsewhere I meant more like OSS 3.26, 3.25, 3.24. Sorry, should have made that clearer. Assuming that this applies to those versions, copy the changes and we're good to go.
> 
> @StevenTigera



> > Is this something that came up in testing for 3.27? Should we make corresponding changes elsewhere?
> 
> By elsewhere I meant more like OSS 3.26, 3.25, 3.24. Sorry, should have made that clearer. Assuming that this applies to those versions, copy the changes and we're good to go.
> 
> @StevenTigera

NP @ctauchen - this is now done thanks and should be all good to merge

**Pull request merged**
