### PR TITLE
DOCS-2055-add-cc-support-policy

### PR DESCRIPTION
**Pull request by bmckercher123**
Product Version(s):

Issue:
https://tigera.atlassian.net/browse/DOCS-2055

Link to docs preview:
Upgrade cluster: https://deploy-preview-1242--tigera.netlify.app/calico-cloud/get-started/upgrade-cluster
Support policy 2022: https://deploy-preview-1242--tigera.netlify.app/calico-cloud/get-started/support-policy-2022
Support policy 2021: https://deploy-preview-1242--tigera.netlify.app/calico-cloud/get-started/support-policy-2021

Link to tigera website support policy: https://www.tigera.io/legal/calico-cloud-support-policy-february-16-2021-february-18-2022/

SME review:
- [ ] An SME has approved this change. 

DOCS review:
- [ ] A member of the docs team has approved this change.

Additional information:

Merge checklist:

- [ ] Deploy preview inspected wherever changes were made 
- [ ] Build completed successfully
- [ ] Test have passed

### CODE REVIEW

**Review by ctauchen — COMMENTED** [review]
A few general thoughts: 
* I don't think we should host the support policy on the docs site. That's really a matter for Support/Legal, and it's already hosted on tigera.io. Duplicates create opportunity for error.
* I don't think the screenshot, or that particular mention of 26 days, is useful.

The main content question is whether/how we indicate the support period. This is quite a difficult idea to get across, considering how it's pegged to CE releases. At the moment, there's no way for a user to figure out what CC version is related to what CE version. We should consider carefully how a user could read the upgrade statement and what conclusions they could arrive at.

What may be best for the docs site to point to the relevant area of the support policy. I'm not sure we should be in the business of interpreting the support policy.

**Comment by bmckercher123** [comment]
@ctauchen I agree about the duplication. I was thinking that the Support policy should be on the docs site (not Tigera site...who would think to search the Marketing site for a policy that applies when you become a customer). Plus, we have the Support policy for CE on the docs site. I was going to ask the Tigera website to remove the duplication. Regarding interpretation of the Support policy, I've punted that back to Erik and Phil to align.

**Comment by ctauchen** [comment]
> @ctauchen I agree about the duplication. I was thinking that the Support policy should be on the docs site (not Tigera site...who would think to search the Marketing site for a policy that applies when you become a customer). Plus, we have the Support policy for CE on the docs site. I was going to ask the Tigera website to remove the duplication. Regarding interpretation of the Support policy, I've punted that back to Erik and Phil to align.

I think we're blurring the lines between 1) the support policy, a legal document that describes the terms of a support agreement; and 2) a documentation reference that describes what platforms, infrastructure, software, settings, etc works with ("is supported by") our software product.

The CE support policy (of type 1) appears to be this: https://www.tigera.io/legal/support-policy/. What we maintain in the CE docs is more of the second type.

I favor keeping the legal document on the corporate site.

**Comment by bmckercher123** [comment]
Closing this PR. The alignment of Support policy language still needs to align with the UI notice so users understand. I will open backlog Eng ticket.

**Pull request closed without merging**
