### PR TITLE
fix helm cunstomization - number of replicas

### PR DESCRIPTION
**Pull request by ti-afra**
Product Version(s):

Issue:

Link to docs preview:

SME review:
- [ ] An SME has approved this change. 

DOCS review:
- [ ] A member of the docs team has approved this change.

Additional information:

Merge checklist:

- [ ] Deploy preview inspected wherever changes were made 
- [ ] Build completed successfully
- [ ] Test have passed

### CODE REVIEW

**Comment by ctauchen** [comment]
Hi @ti-afra ! Do you have a ticket linked to this change? I'm not quite sure what this is about.

Assuming it's all good, does this need to go in other CE or CC docs?

**Review by bmckercher123 — APPROVED** [review]
LGTM. If the change here is only for 3.19, then copy to CC 3.19 folder as well.

**Comment by ti-afra** [comment]
> Hi @ti-afra ! Do you have a ticket linked to this change? I'm not quite sure what this is about.
> 
> Assuming it's all good, does this need to go in other CE or CC docs?

here is a ticket I created for tracking this issue: https://tigera.atlassian.net/browse/EV-4225

it is calico enterprise from 3.18.

**Comment by ti-afra** [comment]
> LGTM. If the change here is only for 3.19, then copy to CC 3.19 folder as well.

Updated CE 3.18 as well. this is only Calico Enterprise docs at this point.

**Pull request merged**
