### PR TITLE
Fix rbac version - EV-3491

### PR DESCRIPTION
**Pull request by vara2504**
Product Version(s):

Issue:

Updating the missed files with rbac version.

https://tigera.atlassian.net/browse/EV-3491

SME review:
- [x] An SME has approved this change. 

DOCS review:
- [x] A member of the docs team has approved this change.

Additional information:

Merge checklist:

- [x] Deploy preview inspected wherever changes were made 
- [x] Build completed successfully
- [x] Tests have passed

### CODE REVIEW

**Comment by ctauchen** [comment]
@vara2504 The bug's fixVersion is 3.16.2. Is that because this docs change is relevant only for that patch? If so, then we'll need to be careful about timing for how we merge these changes. But it kinda looks like this is just a bug that ought to be changed immediately.
CC @bmckercher123

**Comment by vara2504** [comment]
@ctauchen :  it is applicable for both next and 3.16.2 .. 
The fix was made in calico-private manifest -https://github.com/tigera/calico-private/pull/6044 .. RBAC version is updated from v1betav1 to v1.  Docs had few yaml blocks with cluster role binding which is missed at that point of time.

initial fix - https://github.com/tigera/calico-private/pull/6044 - is available in both next and 3.16.2

**Comment by bmckercher123** [comment]
3.16.2 will not release until end of May. Hold this PR until then.

**Comment by vara2504** [comment]
@bmckercher123 Sorry i conveyed it wrong.. This change is applicable for both 3.16 and 3 17.. it is a bug in the existing docs which need to be fixed.. 
RBAC version should be` rbac.authorization.k8s.io/v1` instead of `apiVersion: rbac.authorization.k8s.io/v1beta1` 
For example: 3.16 federation yaml have a correct version.
https://docs.tigera.io/calico-enterprise/latest/multicluster/federation/kubeconfig#create-access-to-secrets-for-clusters

**Comment by ctauchen** [comment]
@vara2504 So it sounds like all instances of `rbac.authorization.k8s.io/v1beta1` must be changed to `rbac.authorization.k8s.io/v1`.

This applies to 
* CE 3.16
* CE 3.17
* CC/3.16
* CC/3.17

If that's the case, then let's make sure those changes are made throughout those versions. The current changes do not capture everything in the relevant versions.

For example: https://deploy-preview-623--tigera.netlify.app/calico-cloud/compliance/overview#configure-report-permissions

**Comment by vara2504** [comment]
@ctauchen yes you are correct.. Sorry for missing it earlier.. i will update all the needed files now. Also update 3.15 files as @rene have made the changes for 3.15 manifest -https://github.com/tigera/calico-private/pull/6046

**Review by bmckercher123 — APPROVED** [review]
LGTM.

**Pull request merged**
