### PR TITLE
DOCS-1383: Remove valid/fixed links from the skip list

### PR DESCRIPTION
**Pull request by girishshankaran**
Product Version(s):

Issue:
https://tigera.atlassian.net/browse/DOCS-1383

Link to docs preview:

SME review:
- [ ] An SME has approved this change. 

DOCS review:
- [ ] A member of the docs team has approved this change.

Additional information:

### CODE REVIEW

**Comment by ctauchen** [comment]
Looking at the deploy logs, it appears the the `kube-flannel-rbac.yaml` link remains dead.

**Comment by girishshankaran** [comment]
> Looking at the deploy logs, it appears the the `kube-flannel-rbac.yaml` link remains dead.

The link is fixed in OS 3.24 branch. It's breaking again because I need to make the fix in other branches. I'll do that.

**Comment by girishshankaran** [comment]
https://github.com/projectcalico/calico/pull/7530 - for OS master branch

**Comment by girishshankaran** [comment]
> Looking at the deploy logs, it appears the the `kube-flannel-rbac.yaml` link remains dead.

@ctauchen I put it back into the skip list. Can we merge it?

**Comment by girishshankaran** [comment]
This is more valid.

**Pull request closed without merging**
