### PR TITLE
Add browser support section for Calico Enterprise

### PR DESCRIPTION
**Pull request by sabags**
Update browser list for Calico Cloud

Product Version(s):
Calico Enterprise
Calico Cloud

Issue:
N/A

Link to docs preview:

SME review:
- [ ] An SME has approved this change. 

DOCS review:
- [ ] A member of the docs team has approved this change.

Additional information:

Merge checklist:

- [ ] Deploy preview inspected wherever changes were made 
- [ ] Build completed successfully
- [ ] Test have passed

### CODE REVIEW

**Review by tmjd — APPROVED** [review]
Its fine with me to reorder the list for CC to match what is being added to Enterprise.

**Review by rene-dekker — APPROVED** [review]
lgtm

**Comment by sabags** [comment]
@ctauchen : waiting on your review before this can be merged. Actually I don't have merge permissions so if it looks good to you approve and merge please ?

**Comment by ctauchen** [comment]
I'm still waiting for feedback from @tigeraphil about the broader question of browser support. Once that's resolved we can move on this.

**Comment by ctauchen** [comment]
@sabags See https://github.com/tigera/docs/pull/1079/files

Phil mentions lack of testing, so perhaps if that's changed then we're good to restore. But I'd like to hear that from him.

**Pull request merged**
