### PR TITLE
GH#8432: remove unknown field 'spec.etcdv3CompactionPeriod'

### PR DESCRIPTION
**Pull request by sebhoss**
Product Version(s): Calico

Issue: https://github.com/projectcalico/calico/issues/8432

Link to docs preview: https://deploy-preview-1266--calico-docs-preview-next.netlify.app/calico/next/reference/resources/kubecontrollersconfig

SME review:
- [ ] An SME has approved this change. 

DOCS review:
- [ ] A member of the docs team has approved this change.

Additional information:

Merge checklist:

- [ ] Deploy preview inspected wherever changes were made 
- [ ] Build completed successfully
- [ ] Test have passed

### CODE REVIEW

**Comment by ctauchen** [comment]
@caseydavenport PTAL

Specifically: Does this change apply to OSS 3.25+? Or is this a recent change?

**Comment by caseydavenport** [comment]
@sebhoss my apologies, I did a bit of a closer look at this API and realized the field _does_ exist, but that the capitalization in the documentation is what is wrong. 

Here's the code link: https://github.com/projectcalico/calico/blob/126ddced8d2f070f34482bb2076f65a0f8d4d596/api/pkg/apis/projectcalico/v3/kubecontrollersconfig.go#L57-L58

The docs change should be `etcdv3CompactionPeriod` -> `etcdV3CompactionPeriod`

**Comment by sebhoss** [comment]
oh thanks for taking a second look! I force pushed into my fork to fix the capitalization ^^

**Review by caseydavenport — APPROVED** [review]
Looks good, thank you!

**Comment by caseydavenport** [comment]
@ctauchen this applies to all versions of Calico OSS

**Comment by sebhoss** [comment]
rebased on latest main to fix merge conflicts

**Comment by ctauchen** [comment]
LGTM, thanks @sebhoss !

**Pull request merged**
