### PR TITLE
docs: adding timeout to the typha server TLS handshake

### PR DESCRIPTION
**Pull request by rodrigorfk**
Product Version(s):

Issue: 
- https://github.com/projectcalico/calico/issues/7908
- https://github.com/projectcalico/calico/pull/7909

Link to docs preview:

SME review:
- [x] An SME has approved this change. 

DOCS review:
- [x] A member of the docs team has approved this change.

Additional information:

Merge checklist:

- [x] Deploy preview inspected wherever changes were made 
- [x] Build completed successfully
- [x] Test have passed

### CODE REVIEW

**Comment by bmckercher123** [comment]
@rodrigorfk Your first contribution! Thank you for being engaged in Calico docs. I've assigned a SME to review it.

**Comment by fasaxc** [comment]
Change looks good, great of you to seek out and update the docs!  Just waiting for the code change PR to be approved before this is ready to merge.

**Review by fasaxc — APPROVED** [review]
Code change is in so this is approved from my PoV (but I think the change might be to the wrong copy of the docs; it should go into the OS docs too...)

**Comment by bmckercher123** [comment]
@rodrigorfk The change you have also apply to Calico Open Source docs. Please copy the doc changes to calico root level folder (3.27) and then rebase. Then I'll merge it.

**Comment by rodrigorfk** [comment]
> @rodrigorfk The change you have also apply to Calico Open Source docs. Please copy the doc changes to calico root level folder (3.27) and then rebase. Then I'll merge it.

done @bmckercher123, I hope that is the correct file for the Open Source version.

**Review by bmckercher123 — APPROVED** [review]
Yes, this is correct. Approved. Thanks again for contributing to Calico!

**Pull request merged**
