### PR TITLE
Add doc card links for new BFD configuration

### PR DESCRIPTION
**Pull request by caseydavenport**
Missed this in my original PR

Product Version(s):

Issue:

Link to docs preview:

SME review:
- [ ] An SME has approved this change. 

DOCS review:
- [ ] A member of the docs team has approved this change.

Additional information:

Merge checklist:

- [ ] Deploy preview inspected wherever changes were made 
- [ ] Build completed successfully
- [ ] Test have passed

### CODE REVIEW

**Comment by caseydavenport** [comment]
CC @ctauchen @coutinhop

**Review by coutinhop — APPROVED** [review]

**Comment by ctauchen** [comment]
LGTM, pending clean build. I'm clearing the cache and running again.

**Comment by caseydavenport** [comment]
@ctauchen looks like they failed again - any idea what might be going on? Failure seems to be unrelated?

**Comment by ctauchen** [comment]
> @ctauchen looks like they failed again - any idea what might be going on? Failure seems to be unrelated?

Builds passed this time, all good.

**Pull request merged**
