### PR TITLE
Add envXX to MTUIfacePattern

### PR DESCRIPTION
**Pull request by Rajalakshmi-Girish**
Related to https://github.com/projectcalico/calico/pull/7405

### CODE REVIEW

**Comment by ctauchen** [comment]
Hi @Rajalakshmi-Girish ! Thanks for contributing! We'll take a look at your changes and get back to you with questions.

**Comment by ctauchen** [comment]
@caseydavenport Since you've looked at the other incarnation of this, can you review here?

**Comment by caseydavenport** [comment]
@Rajalakshmi-Girish the docs changes look good, but I'm not seeing a PR that was merged that actually changed this - could you link the PR that this is documenting?

**Comment by Rajalakshmi-Girish** [comment]
> @Rajalakshmi-Girish the docs changes look good, but I'm not seeing a PR that was merged that actually changed this - could you link the PR that this is documenting?

https://github.com/projectcalico/calico/pull/7523
The above PR is still open. @caseydavenport Can you PTAL?

**Comment by Rajalakshmi-Girish** [comment]
https://github.com/projectcalico/calico/pull/7523 is still open. :|

**Comment by bmckercher123** [comment]
Sorry about the delay. I will get a SME to help on the base PR.

**Comment by ctauchen** [comment]
@Rajalakshmi-Girish It looks like your PR was merged to projectcalico/calico.

Since your original docs contribution, the docs versions have changed. There are a number of merge conflicts for archived documentation, and we've now created several new versions that aren't currently addressed by this PR.

Can you update your PR to address the new versions and the merge conflicts?

**Comment by ctauchen** [comment]
Added and merged in #1068

**Pull request closed without merging**
