### PR TITLE
[CORE-10573] Add NFLOG metrics + tidy up

### PR DESCRIPTION
**Pull request by fasaxc**
Product Version(s):

Calico OS (just tidy ups)
Calico enterprise v3.20.0-2.0+

Issue:

https://tigera.atlassian.net/browse/CORE-10573

Link to docs preview:

https://deploy-preview-1596--calico-docs-preview-next.netlify.app/calico/next/reference/felix/prometheus
https://deploy-preview-1596--calico-docs-preview-next.netlify.app/calico-enterprise/next/reference/component-resources/node/felix/prometheus

SME review:
- [ ] An SME has approved this change. 

DOCS review:
- [ ] A member of the docs team has approved this change.

Additional information:

Merge checklist:

- [ ] Deploy preview inspected wherever changes were made 
- [ ] Build completed successfully
- [ ] Test have passed

### CODE REVIEW

**Comment by ctauchen** [comment]
@fasaxc Thanks for this. In your comment you say that the Calico OSS changes are "just tidy ups". But it looks like there are a dozen or so new parameters. Was that intentional?

**Comment by fasaxc** [comment]
Sigh, I thought they had just been missed from the OS doc so I copied them over.  But it looks like we've added metrics to Enterprise without upstreaming them :-(  Will fix up.

**Comment by ctauchen** [comment]
Thanks, @fasaxc. I think that organizing the keys by type is a great improvement. But it's tricky add sub-headings inside a table. Did you consider doing this with multiple tables? So instead of one table, you have half a dozen, each introduced by an  h4 heading.

Something like this: 

```
#### Cluster-wide metrics

| Name                                                                 | Description                                                                                                                                                         |
|----------------------------------------------------------------------|---------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| `felix_cluster_num_host_endpoints`                                   | Total number of host endpoints cluster-wide.                                                                                                                        |
| `felix_cluster_num_hosts`                                            | Total number of {{prodname}} hosts in the cluster.                                                                                                                  |
| `felix_cluster_num_policies`                                         | Total number of policies in the cluster.                                                                                                                            |
| `felix_cluster_num_profiles`                                         | Total number of profiles in the cluster.                                                                                                                            |
| `felix_cluster_num_tiers`                                            | Total number of {{prodname}} tiers in the cluster.                                                                                                                  |
| `felix_cluster_num_workload_endpoints`                               | Total number of workload endpoints cluster-wide.                                                                                                                    |

#### General metrics 

| Name                                                                 | Description                                                                                                                                                         |
|----------------------------------------------------------------------|---------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| `felix_active_local_endpoints`                                       | Number of active endpoints (workload+host) on this host.                                                                                                            |
| `felix_active_local_policies`                                        | Number of active policies on this host.  Only "active" policies that match a local endpoint have a significant cost.             
```

**Comment by ctauchen** [comment]
@fasaxc LGTM, thanks! Ready for merge?

**Comment by ctauchen** [comment]
Merging, we'll leave the backports in the backlog. Thanks @fasaxc!

**Pull request merged**
