### PR TITLE
DOCS-2300: Adds changes for Helpful Content Update SEO

### PR DESCRIPTION
**Pull request by ctauchen**
The aim here is to make it easier for users to situate themselves in the documentation, particularly when linking in directly from search. We currently have two context items (product and version) in two different locations: as an item in the breadcrumbs and as a version badge. 

The changes here put them together, making them easier to scan. 

I've made the following code changes:

* I swizzled the `DocVersionBadge` component to include more context than just the version.
* I unswizzled the `DocBreadcrumbs` component, which we had modified in an attempt to provide some of this context. I think this version works better.

Deploy preview: https://deploy-preview-1616--tigera.netlify.app/

Current:
image
----
Proposed:
image
----
Proposed v2:
image
----

### CODE REVIEW

**Comment by ronanc-tigera** [comment]
@ctauchen can you attach a screenshot?

**Comment by ctauchen** [comment]
> @ctauchen can you attach a screenshot?

Done!

**Comment by ctauchen** [comment]
PTAL @ronanc-tigera 
CC @doucol

**Comment by ctauchen** [comment]
@ronanc-tigera SEO folks requested that the text be at least 13px. 
* Can you take a look at my CSS changes?
* How does this look to you? I'm mostly ambivalent. See "Proposed v2" above.

**Review by ronanc-tigera — APPROVED** [review]

**Pull request merged**
