### PR TITLE
[EV-2876] Add vdom parameter mention to Fortigate

### PR DESCRIPTION
**Pull request by dimitri-nicolo**
- Add Vdom parameter to fortigate
- For 3.16 Calico Enterprise and 3.16 Calico Cloud

### CODE REVIEW

**Review by bmckercher123 — APPROVED** [review]
LGTM. It looks like this is for CC 3.15, correct?

**Review by bmckercher123 — CHANGES_REQUESTED** [review]
\

**Review by bmckercher123 — DISMISSED** [review]
LGTM

**Review by bmckercher123 — APPROVED** [review]
LGTM

**Comment by ctauchen** [comment]
@dimitri-nicolo @bmckercher123 Thanks for this. I'd like to hold off on the merge until I can get the CC 3.16 content structure in place. I'll have this ready on Thursday and will follow up with instructions then.

**Review by bmckercher123 — APPROVED** [review]
Approve

**Comment by ctauchen** [comment]
@bmckercher123 Does this also need to go in CC 3.16?

**Comment by dimitri-nicolo** [comment]
> @bmckercher123 Does this also need to go in CC 3.16?

@ctauchen yes please!

**Pull request merged**
