### PR TITLE
Update ipamconfig.mdx

### PR DESCRIPTION
**Pull request by ehsan310**
According to my discussion with tigera developers the default limit is not unlimited it is 20.

Product Version(s):

Issue:

Link to docs preview:

SME review:
- [ ] An SME has approved this change. 

DOCS review:
- [ ] A member of the docs team has approved this change.

Additional information:

Merge checklist:

- [ ] Deploy preview inspected wherever changes were made 
- [ ] Build completed successfully
- [ ] Test have passed

### CODE REVIEW

**Comment by ehsan310** [comment]
@tigera/docs for approval

**Comment by ehsan310** [comment]
> ### ❌ Deploy Preview for _tigera_ failed. **[Why did it fail? →](https://app.netlify.com/sites/tigera/deploys/66cd78763d3d5d00081e60fb?deploy_diagnostics=true)**
> Built [without sensitive environment variables](https://docs.netlify.com/configure-builds/environment-variables/#sensitive-variable-policy)
> 
> Name	Link
> 🔨 Latest commit	[95267c6](https://github.com/tigera/docs/commit/95267c6ce91a13d2b1096207b0f2e7cab9aab0b9)
> 🔍 Latest deploy log	https://app.netlify.com/sites/tigera/deploys/66cd78763d3d5d00081e60fb

some issues with the check !?

**Comment by ctauchen** [comment]
> > ### ❌ Deploy Preview for _tigera_ failed. **[Why did it fail? →](https://app.netlify.com/sites/tigera/deploys/66cd78763d3d5d00081e60fb?deploy_diagnostics=true)**
> > Built [without sensitive environment variables](https://docs.netlify.com/configure-builds/environment-variables/#sensitive-variable-policy)
> > Name	Link
> > 🔨 Latest commit	[95267c6](https://github.com/tigera/docs/commit/95267c6ce91a13d2b1096207b0f2e7cab9aab0b9)
> > 🔍 Latest deploy log	https://app.netlify.com/sites/tigera/deploys/66cd78763d3d5d00081e60fb
> 
> some issues with the check !?

Resolved now. The build found a bad link that was not related to your PR. 

@caseydavenport Looks like you were helping @ehsan310 on this in the Calico Users Slack. Care to review?

**Review by caseydavenport — APPROVED** [review]

**Comment by caseydavenport** [comment]
Yep, this is correct

**Comment by ctauchen** [comment]
LGTM, thanks!

**Comment by ctauchen** [comment]
@caseydavenport Am I right to assume this applies to all current version? I'll put those fixes in separately.

**Pull request merged**
