### PR TITLE
OSS configure resource request changes

### PR DESCRIPTION
**Pull request by vara2504**
Add csi-node-driver spec
enterprise doc:
https://github.com/tigera/docs/pull/1379

Product Version(s):

Issue:

Link to docs preview:

SME review:
- [ ] An SME has approved this change. 

DOCS review:
- [ ] A member of the docs team has approved this change.

Additional information:

Merge checklist:

- [ ] Deploy preview inspected wherever changes were made 
- [ ] Build completed successfully
- [ ] Test have passed

### CODE REVIEW

**Comment by vara2504** [comment]
@ctauchen I have created a similar doc for OSS. And add a component that was missed previous in EE. 
Will create another PR for cloud once get the list of components applicable for calico cloud team.

**Comment by ctauchen** [comment]
Just want to confirm this is intended for OSS 3.28?

**Comment by vara2504** [comment]
@ctauchen  yes it is OSS 3.28 . I have updated the doc for calico cloud too. i could  not test the changes because i see next drop down (when i do yarn start-next) only for enterprise and OSS not for cloud. Am i missing some thing?

**Comment by ctauchen** [comment]
> @ctauchen yes it is OSS 3.28 . I have updated the doc for calico cloud too. i could not test the changes because i see next drop down (when i do yarn start-next) only for enterprise and OSS not for cloud. Am i missing some thing?

Seems there's a bug in that yarn start-next script. For now, look at the deploy preview for version Next: https://deploy-preview-1409--calico-docs-preview-next.netlify.app/calico-cloud/next/reference/component-resources/configure-resources

**Comment by ctauchen** [comment]
Your other build failures are caused by an error that we've fixed. A fetch and rebase should sort you out.

**Comment by vara2504** [comment]
@ctauchen Rebased with the latest change. And fix few [bugs](https://tigera.atlassian.net/projects/CNX?selectedItem=com.atlassian.plugins.atlassian-connect-plugin:com.kanoah.test-manager__main-project-page#!/testPlayer/testExecution/CNX-E5528) . Please take a look and let me know

**Comment by ctauchen** [comment]
LGTM. Ready to merge?

**Comment by vara2504** [comment]
@ctauchen Yes. Should be good to merge

**Pull request merged**
